// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreventPlus.Data;

#nullable disable

namespace PreventPlus.Migrations
{
    [DbContext(typeof(PreventPlusContext))]
    [Migration("20250608023623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PreventPlus.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriacaoAlerta")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdNotificacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MensagemAlerta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificacaoIdNotificacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAlerta");

                    b.HasIndex("NotificacaoIdNotificacao");

                    b.ToTable("ALERTA", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Checklist", b =>
                {
                    b.Property<int>("IdChecklist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoChecklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusChecklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloChecklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdChecklist");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("CHECKLIST", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Dica", b =>
                {
                    b.Property<int>("IdDica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConteudoDica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriacaoDica")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdDesastre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDesastreIdDesastre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoDica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloDica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDica");

                    b.HasIndex("TipoDesastreIdDesastre");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("DICA", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.HistoricoRisco", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistAlerta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistChuva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistImpacto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistTemp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistUmidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegiaoIdRegiao")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHistorico");

                    b.HasIndex("RegiaoIdRegiao");

                    b.ToTable("HISTORICO_RISCO", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Kit", b =>
                {
                    b.Property<int>("IdKit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemKit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdKit");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("KIT", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.LocalFavorito", b =>
                {
                    b.Property<int>("IdFav")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLocal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalSeguroIdLocal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdFav");

                    b.HasIndex("LocalSeguroIdLocal");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("LOCAL_FAVORITO", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.LocalSeguro", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnderecoLocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeLocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoLocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdLocal");

                    b.ToTable("LOCAL_SEGURO", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescNotificacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnvioNotificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TituloNotificacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Regiao", b =>
                {
                    b.Property<int>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoRegiao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeRegiao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRegiao");

                    b.ToTable("REGIAO", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.TipoDesastre", b =>
                {
                    b.Property<int>("IdDesastre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDesastre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDesastre");

                    b.ToTable("TIPO_DESASTRE", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegiaoIdRegiao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UsuarioCriado")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("RegiaoIdRegiao");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PreventPlus.Models.Alerta", b =>
                {
                    b.HasOne("PreventPlus.Models.Notificacao", "Notificacao")
                        .WithMany("Alertas")
                        .HasForeignKey("NotificacaoIdNotificacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notificacao");
                });

            modelBuilder.Entity("PreventPlus.Models.Checklist", b =>
                {
                    b.HasOne("PreventPlus.Models.Usuario", "Usuario")
                        .WithMany("Checklists")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PreventPlus.Models.Dica", b =>
                {
                    b.HasOne("PreventPlus.Models.TipoDesastre", "TipoDesastre")
                        .WithMany("Dicas")
                        .HasForeignKey("TipoDesastreIdDesastre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreventPlus.Models.Usuario", "Usuario")
                        .WithMany("Dicas")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDesastre");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PreventPlus.Models.HistoricoRisco", b =>
                {
                    b.HasOne("PreventPlus.Models.Regiao", "Regiao")
                        .WithMany("HistoricosRisco")
                        .HasForeignKey("RegiaoIdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("PreventPlus.Models.Kit", b =>
                {
                    b.HasOne("PreventPlus.Models.Usuario", "Usuario")
                        .WithMany("Kits")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PreventPlus.Models.LocalFavorito", b =>
                {
                    b.HasOne("PreventPlus.Models.LocalSeguro", "LocalSeguro")
                        .WithMany("LocaisFavoritos")
                        .HasForeignKey("LocalSeguroIdLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreventPlus.Models.Usuario", "Usuario")
                        .WithMany("LocaisFavoritos")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalSeguro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PreventPlus.Models.Notificacao", b =>
                {
                    b.HasOne("PreventPlus.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PreventPlus.Models.Usuario", b =>
                {
                    b.HasOne("PreventPlus.Models.Regiao", "Regiao")
                        .WithMany("Usuarios")
                        .HasForeignKey("RegiaoIdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("PreventPlus.Models.LocalSeguro", b =>
                {
                    b.Navigation("LocaisFavoritos");
                });

            modelBuilder.Entity("PreventPlus.Models.Notificacao", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("PreventPlus.Models.Regiao", b =>
                {
                    b.Navigation("HistoricosRisco");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PreventPlus.Models.TipoDesastre", b =>
                {
                    b.Navigation("Dicas");
                });

            modelBuilder.Entity("PreventPlus.Models.Usuario", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Dicas");

                    b.Navigation("Kits");

                    b.Navigation("LocaisFavoritos");

                    b.Navigation("Notificacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
